include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_empty_else
    - avoid_web_libraries_in_flutter
    - always_declare_return_types
    - avoid_catches_without_on_clauses
    - void_checks
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - empty_statements
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_relative_imports
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors