name: gerador_de_times
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+2

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  micro_core:
    path: packages/micro_core
  micro_app_welcome:
    path: packages/micro_app_welcome
  micro_app_login:
    path: packages/micro_app_login
  micro_app_register:
    path: packages/micro_app_register
  micro_app_nav:
    path: packages/micro_app_nav
  micro_subscription:
    path: packages/micro_subscription
  micro_app_cup:
    path: packages/micro_app_cup
  micro_app_config_cup:
    path: packages/micro_app_config_cup
  micro_app_game:
    path: packages/micro_app_game
  micro_help:
    path: packages/micro_help

  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/sounds/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular_0.ttf
        - asset: assets/fonts/poppins_bold_0.ttf
          weight: 800
        - asset: assets/fonts/poppins_light_0.ttf
          weight: 200

    - family: Inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf
        - asset: assets/fonts/inter_bold.ttf
          weight: 800
        - asset: assets/fonts/inter_light.ttf
          weight: 200

flutter_native_splash:
  flutter_native_splash:
  image: "assets/images/icon_splash_screen.png"
  color: "4780EA"
  android_disable_fullscreen: true
