name: dependencies
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^4.1.0
  lottie: ^1.1.0
  iconsax: ^0.0.8
  modal_bottom_sheet: ^2.0.0
  adaptive_action_sheet: ^2.0.0
  in_app_review: ^2.0.4
  carousel_slider: ^4.0.0
  countdown_progress_indicator: ^0.1.2
  google_sign_in: ^5.3.0
  loading_indicator: ^3.0.3
  cached_network_image: ^3.2.0
  animated_toggle_switch: ^0.5.2
  uuid: ^3.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
